---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:v0.4.1
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-amd64.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
    prerelease: true
  when:
    event:
    - tag
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - "refs/tags/*"

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/terraform-controller
    tag: "${DRONE_TAG}-amd64"
    username:
      from_secret: docker_username
  when:
    event:
    - tag
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - "refs/tags/*"

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: rancher/dapper:v0.4.1
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-arm64.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
    prerelease: true
  when:
    event:
    - tag
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - "refs/tags/*"

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/terraform-controller
    tag: "${DRONE_TAG}-arm64"
    username:
      from_secret: docker_username
  when:
    event:
    - tag
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - "refs/tags/*"

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: rancher/dapper:v0.4.1
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-arm.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
    prerelease: true
  when:
    event:
    - tag
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - "refs/tags/*"

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/terraform-controller
    tag: "${DRONE_TAG}-arm"
    username:
      from_secret: docker_username
  when:
    event:
    - tag
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - "refs/tags/*"

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: rancher/dapper:v0.4.1
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: stage-binaries
  pull: default
  image: rancher/dapper:v0.4.1
  commands:
  - "cp -r ./bin/* ./package/"
  when:
    event:
    - tag

- name: publish-terraform-controller-image
  pull: default
  image: plugins/docker
  settings:
    context: package/
    dockerfile: package/Dockerfile.controller
    password:
      from_secret: docker_password
    repo: rancher/terraform-controller
    tag: "${DRONE_TAG}"
    username:
      from_secret: docker_username
  when:
    event:
    - tag

- name: publish-terraform-executor-image
  pull: default
  image: plugins/docker
  settings:
    context: package/
    dockerfile: package/Dockerfile.executor
    password:
      from_secret: docker_password
    repo: rancher/terraform-controller-executor
    tags:
    - "${DRONE_TAG}"
    - latest
    username:
      from_secret: docker_username
  when:
    event:
    - tag

- name: publish-terraform-appliance-image
  pull: default
  image: plugins/docker
  settings:
    context: package/
    dockerfile: package/Dockerfile.appliance
    password:
      from_secret: docker_password
    repo: rancher/terraform-controller-appliance
    tags:
    - "${DRONE_TAG}"
    - latest
    username:
      from_secret: docker_username
  when:
    event:
    - tag

- name: github_binary_prerelease
  pull: default
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    files:
    - "bin/*"
    prerelease: true
  when:
    event:
    - tag
    ref:
    - "refs/tags/*rc*"
    - "refs/tags/*alpha*"

- name: github_binary_release
  pull: default
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    files:
    - "bin/*"
  when:
    event:
    - tag
    ref:
      include:
      - "refs/tags/v*"
      exclude:
      - "refs/tags/*rc*"
      - "refs/tags/*alpha*"

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  image: plugins/manifest:1.0.2
  settings:
    password:
      from_secret: docker_password
    platforms:
    - linux/amd64
    - linux/arm64
    - linux/arm
    target: "rancher/terraform-controller:${DRONE_TAG}"
    template: "rancher/terraform-controller:${DRONE_TAG}-ARCH"
    username:
      from_secret: docker_username
  when:
    event:
    - tag
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - "refs/tags/*"

depends_on:
- amd64
- arm64
- arm

...
