apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: terraform-controller
  name: terraform-controller
  namespace: terraform-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      run: terraform-controller
  template:
    metadata:
      labels:
        run: terraform-controller
    spec:
      serviceAccountName: terraform-controller
      containers:
        - image: absaoss/terraform-controller:v0.0.17-beta8
          name: terraform-controller
          command: ["terraform-controller"]
