apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    apps.kubernetes.io/component: controller
    apps.kubernetes.io/name: terraform-operator
  name: terraform-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: terraform-operator
  namespace: tf-operator
