apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    run: terraform-operator
  name: terraform-operator
  namespace: tf-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      run: terraform-operator
  template:
    metadata:
      labels:
        run: terraform-operator
        version: v0.0.0
    spec:
      containers:
        - image: cloudnautique/terraform-operator:dev
          imagePullPolicy: Always
          name: terraform-operator
          args: ["--namespace", "tf-operator"]
